services:
  calendar.db:
    image: postgres
    container_name: calendar.db
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  calendar.api:
    container_name: calendar.api
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    expose:
      - 3000
    depends_on:
      - calendar.db

  calendar.web:
    container_name: calendar.web
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres-data:
