FROM node:18 as build

WORKDIR /app

COPY . .

RUN yarn

RUN yarn build:schema

RUN yarn frontend build --configuration=production

FROM nginx:latest

COPY --from=build /app/frontend/dist/calendar-app-frontend/browser /usr/share/nginx/html

EXPOSE 80